"use client"
import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter()
  const onClick = (url) => {
    router.push(url)
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full flex justify-center content-center justify-items-center'>
          <div className='w-11/12 flex justify-start flex-col'>
            <ul className='list-disc pl-10 mb-5 mt-5'>
              <li>
                <Link href={'/'}>Home</Link>
              </li>
              <li>
                <Link href={'/dashboard'}>Dashboard</Link>
              </li>
              <li>
                <Link href={'/calculator'}>Calculator</Link>
              </li>
              <li>
                <Link href={'/search'}>Search</Link>
              </li>
              <li onClick={() => onClick('/settings')}>
                Settings
              </li>
            </ul>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
